Algoritmo "resolucao_de_exercicios"
//
Var

  largura, comprimento, valor, area, preco : real
  
  


Inicio
  escreva ("Digite a largura do terreno: ")
  leia (largura)
  escreva ("Digite o comprimento do terreo: ")
  leia (comprimento)
  escreva ("Digite o valor do metro quadrado: ")
  leia (valor)
  area <- (largura * comprimento)
  escreval ("Area do terreono: ", area:8:2)
  preco <- (valor * area)
  escreval ("Preco do terreno: ", preco:8:2)
  


Fimalgoritmo